# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angel', '0002_pepito'),
    ]

    operations = [
        migrations.AddField(
            model_name='pepito',
            name='extra',
            field=models.CharField(default='Nada', max_length=200),
            preserve_default=False,
        ),
    ]
